### ISSUE TITLE
order status edge case in order details.

### ISSUE THREAD

**Issue by jcads** [locary-ph/merchant-dashboard#108]
Display a cancelled pill like this 
![image](https://user-images.githubusercontent.com/50954098/132284188-f3b9d60c-fdfe-46d9-aeb1-a0e5726c9322.png)
beside the order status heading if order is cancelled. And remove the "tracker".

_current order status if order is cancelled_
![image](https://user-images.githubusercontent.com/50954098/132285898-5273311d-2440-407e-a3ea-9fedf77d3e56.png)

**Comment by BoJoNVi** [comment]
Okay, got it! I'll make a PR for that 😄
